# Generated by Django 4.1.7 on 2023-04-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
